/**
 * THE CONTRACT - what WalletOps promised its customers. The generator's scenarios and the monitors
 * check the live system against these values. They are independent of the wallet code on purpose:
 * if the wallet and the contract disagree, the wallet is wrong.
 *
 * Do not edit this file to make a ticket go away.
 */

export const CONTRACT_CURRENCIES = ["USD", "EUR", "GBP", "JPY"] as const;
export type ContractCurrency = (typeof CONTRACT_CURRENCIES)[number];

/** Decimal places of each currency's minor unit. */
export const CONTRACT_DECIMALS: Record<ContractCurrency, number> = { USD: 2, EUR: 2, GBP: 2, JPY: 0 };

/** Published fee schedule. */
export const PUBLISHED_FEES = {
  /** Transfers between different customers: 0.25% of the amount, rounded half up, within [min, max]. */
  transferBps: 25,
  transferMinMinor: { USD: 25, EUR: 25, GBP: 20, JPY: 30 } as Record<ContractCurrency, number>,
  transferMaxMinor: { USD: 1000, EUR: 1000, GBP: 800, JPY: 1500 } as Record<ContractCurrency, number>,
  /** Transfers between accounts of the same customer are free. */
  ownAccountTransferFee: 0,
  /** Flat fee per withdrawal. */
  withdrawalMinor: { USD: 100, EUR: 100, GBP: 80, JPY: 150 } as Record<ContractCurrency, number>,
};

/** Published daily outgoing limit per account (transfers + withdrawals, fees excluded, UTC day, inclusive). */
export const PUBLISHED_DAILY_LIMIT_MINOR: Record<ContractCurrency, number> = {
  USD: 500_000,
  EUR: 500_000,
  GBP: 400_000,
  JPY: 750_000,
};

/** Spread on currency conversion, in basis points. */
export const PUBLISHED_FX_SPREAD_BPS = 50;

/** Market reference rates (1 unit in USD). Live rates must stay within FX_BAND of these. */
export const REFERENCE_RATES: Record<ContractCurrency, number> = { USD: 1, EUR: 1.08, GBP: 1.27, JPY: 0.0067 };
export const FX_BAND = 0.1;

/** Service level objectives watched by the monitors. */
export const SLO = {
  windowMinutes: 15,
  minRequests: 8,
  maxErrorRate: 0.2,
  maxP95LatencyMs: 1500,
};

/** A transaction may stay "pending" for at most this long. */
export const MAX_PENDING_SECONDS = 120;
